### ISSUE TITLE
Using IMemoryCache

### ISSUE THREAD

**Issue by sohlae** [joseftw/jos.tokens#1]
Hi Josef, is it a good idea to use the `IMemoryCache` interface to store the access token?

**Comment by joseftw** [comment]
Sure, or if you have multiple instances of your application you could use [IDistributedCache](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-6.0). It could be quite tricky to avoid doing multiple requests to refresh the token when using IDistributedCache though since you most likely would want to do some locking. I would say that IMemoryCache is good enough (one token per instance).

**Comment by sohlae** [comment]
Thank you!

**Comment by sohlae** [comment]
Hi Josef, does the cache stored in the memory of the server gets deleted when it goes into an **idle** state? Our IIS server has an idle timeout set to 20 minutes.

**Comment by joseftw** [comment]
I don't use IIS so I have no clue, maybe you can find more info here?
https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-6.0#use-imemorycache
